### ISSUE TITLE
CommandParameter should be included in the transfer

### ISSUE THREAD

**Issue by limefrogyank** [Wintellect/XamarinSamples#11]
I hacked it by replacing the storing of the ICommand in the Dictionary to keeping a reference to the original ToolbarItem instead.  

```
readonly Dictionary<UIBarButtonItem, ToolbarItem> _buttonCommands = new Dictionary<UIBarButtonItem, ToolbarItem>();
```

In `ViewWillAppear`, replace the original adding to the dictionary line with:
`
_buttonCommands.Add(button,tool);
`

Then change this method to:

```
void ToolClicked(object sender, EventArgs args)
{
       var tool = sender as UIBarButtonItem;
       var command = _buttonCommands[tool].Command;
       command.Execute(_buttonCommands[tool].CommandParameter);
}
```

Seems to work ok.  

FYI, thank you for this sample.  It was invaluable for learning how to work with native iOS through Xamarin.Forms... especially for this iOS newbie.

**Comment by KeithJRome** [comment]
Thanks. If you would like to submit a pull request with that improvement, then I'd be happy to accept it into the sample.

**Comment by KeithJRome** [comment]
Thanks! Your PR was merged.
